services:
  web:
    image: website
    build:
      context: .
      dockerfile: ./Dockerfile
    stdin_open: true
    tty: true
    volumes:
      - .:/app:rw
    ports:
      - "8080:8080"
    network_mode: "host"        
